package Logica;

import java.io.Serializable;
import java.sql.SQLException;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import BD.BDInscripciones;
import BD.BDJugador;

import com.vaadin.annotations.AutoGenerated;

public class Inscripcion implements Serializable {

	int id;

	Partido partido;

	Jugador jugador;

	boolean inscripto = false;
	boolean confirmado = false;
	
	public boolean isConfirmado() {
		return confirmado;
	}

	public void setConfirmado(boolean confirmado) {
		this.confirmado = confirmado;
	}

	public Inscripcion() {

	}

	public boolean isInscripto() {
		return inscripto;
	}

	public Inscripcion(int id, Partido partido, Jugador jugador,
			boolean inscripto) {

		this.id = id;
		this.partido = partido;
		this.jugador = jugador;
		this.inscripto = inscripto;
	}

	public void setInscripto(boolean inscripto) {
		this.inscripto = inscripto;
	}

	public void inscribirA(Jugador jugador, Partido partido)
			throws SQLException {
		this.setInscripto(partido.inscribirA(jugador, this));
		this.setJugador(jugador);
		this.setPartido(partido);
	}

	public Partido getPartido() {
		return partido;
	}

	public void setPartido(Partido partido) {
		this.partido = partido;
	}

	public Jugador getJugador() {
		return jugador;
	}

	public int getID() {
		Jugador jugador = this.getJugador();
		Partido partido = this.getPartido();
		BDInscripciones bd;
		try {
			bd = new BDInscripciones();
			bd.getConnection();
			int id = bd.getID(jugador.getDNI(), partido.getNombre(),partido.getLugar(),partido.getFecha());
			return id;
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return -1;
		}
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	public void crearInscripcion(Inscripcion inscripcion, Jugador jugador,
			Partido partido, boolean inscripto) {
		inscripcion.setJugador(jugador);
		inscripcion.setPartido(partido);
		inscripcion.setInscripto(inscripto);

		// Agrego a la bd
		BDJugador bd;
		try {
			bd = new BDJugador();
			bd.getConnection();
			bd.crearInscripcion(jugador.DNI, partido, this);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void borrarInscripcion(Inscripcion ins) {
		BDInscripciones bd;
		try {
			bd = new BDInscripciones();
			bd.getConnection();
			bd.BorrarInscripcion(ins);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void setId(int id) {
		this.id = id;
	}

}
